### ISSUE TITLE
Support parsing inner classes 

### ISSUE THREAD

**Issue by chase-ok** [duchess-rs/duchess#12] opened 2023-04-13 04:33 UTC
Java inner class names are written as `OuterClass$InnerClass`. It looks like our javap parser is failing on the `$` token in type names:

```
error: invalid token `... .invoke.TypeDescriptor <<< $ >>> OfField<java.lang.Clas ...` at offset 1
   --> src/java/lang.rs:125:1
    |
```

**Comment by fpoli** [comment] 2023-04-14 09:39
Adding `$` (and `_`) to the grammar leads to errors like the folowing, because not all valid Java identifiers are valid Rust identifiers. This case is very common when the Java classes are compiled from Scala code.
```
 --> src/main.rs:1:1
  |
1 | / duchess::java_package! {
2 | |     package viper.silver.frontend;
3 | |     class DefaultFrontend { * }
4 | | }
  | |_^
  |
  = help: message: `"DefaultFrontend$Succ$"` is not a valid identifier

error: could not compile `duchess-client` due to previous error
```

To solve this, `duchess` could by default try some string replacements (`$ => _eq_`), but the result might still clash with existing Java identifiers. It would be nice to allow the user renamig such bad Rust identifiers. For example:
```rust
duchess::java_package! {
    package viper.silver.frontend;
    class DefaultFrontend { _program_$eq as program_set, * }
    class DefaultFrontend$Succ$ as DefaultFrontendSucc { * }
}
```

**Comment by nikomatsakis** [comment] 2023-04-21 10:07
Fixed in #25

**Comment by fpoli** [comment] 2023-05-05 09:03
Classes with a `$` in their name in the output of `javap` are now parsed correctly, but not when they are written in a `java_package!` macro.

Example:
```rust
java_package!{
    package foo;
    class NoopReporter$ {}
}
```
Error:
```
error: unexpected token `class NoopReporter  <<< $ >>>  {}` at offset 19, expected one of `["\".\"", "\"<\"", "\"extends\"", "\"implements\"", "\"{\""]`
```

The error is caused by the extra whitespaces that are added when printing a token stram. That is, duchess calls `parse_class_decl` passing `"class NoopReporter $ {}"`, which contains a space before the `$`.

**Comment by nikomatsakis** [comment] 2023-05-15 10:00
@fpoli is this issue fixed now?

**Comment by fpoli** [comment] 2023-05-15 11:31
Yes, this can be closed.

**Closed** 2023-05-15 22:55 UTC
Labels: good first issue
